spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://localhost:3306/crm?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password

# Updated management endpoints
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/appinfo
management.endpoints.web.exposure.exclude=env,beans

# Updated Thymeleaf properties
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
