# Production environment configuration
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.thymeleaf.cache=true

# Disable development features
spring.h2.console.enabled=false

# Disable showing SQL for security
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logging
logging.level.org.springframework.web=WARN
logging.level.crm=INFO

# Security
server.ssl.enabled=true
server.ssl.key-store=${SERVER_SSL_KEYSTORE}
server.ssl.key-store-password=${SERVER_SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat