apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-crm-008-ingress
  namespace: test-crm-008
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /appinfo/health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
  labels:
    app: test-crm-008
spec:
  rules:
  - host: test-crm-008.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-crm-008-service
            port:
              number: 80
